routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/x', function() {
	echo '<form method="post" action="/z">name: <input name="name"/><button type="submit">ok</button></form>';
});

Route::get('/y', 'ProductController@yy');

Route::post('/z', 'ProductController@zz');

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('home');
});

    Route::get('/inventory/report', 'ProductController@report');


Route::group(['middleware' => 'auth'], function () {
  Route::resource('inventory', 'ProductController');

  Route::post('/inventory/{id}/edit', 'ProductController@update');
  Route::post('sale/today', 'SaleController@today')->name('sale.today');
  Route::resource('sales', 'SaleController', ['names' => ['destroy' => 'sale.destroy']]);
  Route::post('/sales/create', 'SaleController@store')->name('sale.create');
  Route::get('/sale/report', 'SaleController@report');

  Route::get('/', 'ProductController@index');


  Route::resource('user', 'StaffController');
  Route::post('/user/{id}/edit', 'StaffController@update');
  Route::get('/', 'StaffController@index');

  //Route::get('/report', 'ReportController@pdf');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout');

resources/views/errors.blade.php
@if (count($errors))
<div class="card bg-danger text-white mb-3">
  <div class="card-body">
    @foreach ($errors->all() as $error)
      <li>{{$error}}</li>
    @endforeach
  </div>
</div>
@endif

resources/views/home.blade.php
<?php

use App\Product;
use App\Sale;


?>

@extends('layouts.layout')
@section('content')
                <div class="col-md-12" style="padding:20px;">
                    <div class="col-md-12 padding-0">
                        <div class="col-md-8 padding-0">
                            <div class="col-md-12 padding-0">
                                <div class="col-md-6">
                                    <div class="panel box-v1">
                                      <div class="panel-heading bg-white border-none">
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                          <h4 class="text-left">Inventory</h4>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                           <h4>
                                           <span class="icon-user icons icon text-right"></span>
                                           </h4>
                                        </div>
                                      </div>
                                      <div class="panel-body text-center">
                                        <h1>{{ Product::get()->count() }}</h1>
                                        <p>Total Product</p>
                                        <hr/>
                                      </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="panel box-v1">
                                      <div class="panel-heading bg-white border-none">
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                          <h4 class="text-left">Sales</h4>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                           <h4>
                                           <span class="icon-basket-loaded icons icon text-right"></span>
                                           </h4>
                                        </div>
                                      </div>
                                      <div class="panel-body text-center">
                                        <h1>RM {{ Sale::all()->sum(function($t){return $t->price * $t->quantity; }) }}</h1>
                                        <p>Total Sales</p>
                                        <hr/>
                                      </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="panel box-v1">
                                      <div class="panel-heading bg-white border-none">
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-left padding-0">
                                          <h4 class="text-left">Stock</h4>
                                        </div>
                                        <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                                           <h4>
                                           <span class="icon-basket-loaded icons icon text-right"></span>
                                           </h4>
                                        </div>
                                      </div>
                                      <div class="panel-body text-center">
                                        <h1>200</h1>
                                        <p>Available Stock</p>
                                        <hr/>
                                      </div>
                                    </div>
                                </div>
                            </div>
                          </div>
                        </div>
                      </div>


@endsection

resources/views/master.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Inventory</title>
  <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{ route('inventory.index') }}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {{ Request::is('inventory') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('inventory.index') }}">inventory</a>
      </li>
      <li class="nav-item {{ Request::is('sale') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('sale.index') }}">Total Sales Report</a>
      </li>
      <li class="nav-item {{ Request::is('sale/today') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('sale.today') }}">Todays Report</a>
      </li>
      <li class="nav-item {{ Request::is('inventory/create') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('inventory.create') }}">add items</a>
      </li>
      <li class="nav-item {{ Request::is('sale/create') ? 'active' : ''}}">
        <a class="nav-link" href="{{ route('sale.create') }}">add sales</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a onclick="event.preventDefault(); document.querySelector('form').submit()" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{auth()->user()->name}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <form method="post" action="{{ route('logout') }}" class="d-none">
            @csrf
          </form>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
  @yield('content')

  <div class='bg-dark text-white p-5'>
  </div>
  <script src="{{ asset('js/app.js') }}"></script>
  @yield('script')
</body>
</html>

resources/views/success.blade.php
@if (Session::has('message'))
  <div class="card text-white bg-primary mb-3">
    <div class="card-body">
      <h4>{{Session::get('message')}}</h4>
    </div>
  </div>
@endif