routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/x', function() {
	echo '<form method="post" action="/z">name: <input name="name"/><button type="submit">ok</button></form>';
});

Route::get('/y', 'ProductController@yy');

Route::post('/z', 'ProductController@zz');

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('home');
});

    Route::get('/inventory/report', 'ProductController@report');


Route::group(['middleware' => 'auth'], function () {
  Route::resource('inventory', 'ProductController');

  Route::post('/inventory/{id}/edit', 'ProductController@update');
  Route::post('sale/today', 'SaleController@today')->name('sale.today');
  Route::resource('sales', 'SaleController', ['names' => ['destroy' => 'sale.destroy']]);
  Route::post('/sales/create', 'SaleController@store')->name('sale.create');
  Route::get('/sale/report', 'SaleController@report');

  Route::get('/', 'ProductController@index');


  Route::resource('user', 'StaffController');
  Route::post('/user/{id}/edit', 'StaffController@update');
  Route::get('/', 'StaffController@index');

  //Route::get('/report', 'ReportController@pdf');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout');

app/Sale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sale extends Model
{
  protected $guarded = [];
  protected $appends = ['total'];
  public function getTotalAttribute() {
      return $this->price * $this->quantity;
  }
  public function product() {
    return $this->belongsTo(Product::class);
  }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sale;
use App\Product;
use Session;
use PDF;

class SaleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sales = Sale::orderBy('date', 'desc')->paginate(10);
        return view('sale.index', compact('sales'));
    }
    public function today() {
        $sales = Sale::where('date', date('Y-m-d'))->get();
        return view('sale.index', compact('sales'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::where('quantity', '>',  0)->get();
        return view('sale.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
        'product_id' => 'required',
        'quantity' => 'required',
      ]);
      $product_id = $request->input('product_id');
      $quantity = $request->input('quantity');
      $quantity = $request->input('quantity');
      $product = Product::find($product_id);
      if ($quantity > $product->quantity) {
          return redirect()->back()->withErrors('Asking quantity is more than stock');
      }
      $product->quantity = $product->quantity - $quantity;
      $product->save();
      Sale::create([
        'product_id' => $product_id,
        'quantity' => $quantity,
        'price' => $product->price,
        'date' => date('Y-m-d')
      ]);
      Session::flash('message', 'Sales record added successfully');
      return redirect()->back();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Sale::find($id)->delete();
      Session::flash('message', 'One item delete from sales inventory');
      return redirect()->back();
    }

 public function report()
    {
        $products = Product::get();
        $pdf = PDF::loadView('sale.reportpdf', ['products' => $products]);
        return @$pdf->stream();
    }

}
   /* private function countTotalSale($sales)
    {
        //DEFAULT TOTAL BERNILAI 0
        $total = 0;
        //JIKA DATA ADA
        if ($sales->count() > 0) 
        {
            //MENGAMBIL VALUE DARI TOTAL -> PLUCK() AKAN MENGUBAHNYA MENJADI ARRAY
            $sub_total = $sales->pluck('price')->all();
            //KEMUDIAN DATA YANG ADA DIDALAM ARRAY DIJUMLAHKAN
            $total = array_sum($sub_total);
        }
        return $total;
    }
    ​
    private function countItem($sales)
    {
        //DEFAULT DATA 0
        $data = 0;
        //JIKA DATA TERSEDIA
        if ($sales->count() > 0) {
            //DI-LOOPING
            foreach ($sales as $row) {
                //UNTUK MENGAMBIL QTY 
                $quantity = $row->order_detail->pluck('quantity')->all();
                //KEMUDIAN QTY DIJUMLAHKAN
                $val = array_sum($qty);
                $data += $val;
            }
        } 
        return $data;
    }
    ​
    public function report($report)
    {
        //MENGAMBIL DATA TRANSAKSI BERDASARKAN INVOICE
        $sale = Sale::where('report', $report)
                ->with('id', 'name', 'quantity')->first();
        //SET CONFIG PDF MENGGUNAKAN FONT SANS-SERIF
        //DENGAN ME-LOAD VIEW INVOICE.BLADE.PHP
        $pdf = PDF::setOptions(['dpi' => 150, 'defaultFont' => 'sans-serif'])
            ->loadView('orders.report.invoice', compact('order'));
        return $pdf->stream();
    }
    */

resources/views/sale/create.blade.php
@extends('layouts.layout')
@section('content')
@include('errors')
@include('success')


<div class='container'>
  <div class="col-md-10">
   <div class="col-md-0 top-10">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">
              <div>
    <h3>Add sales</h3>
  </div>
  <form method="post" action="{{ route('sale.create') }}">

    @csrf
    <div class="form-group">
        <label for="product_id">Select a product</label>
        <select name='product_id' class="form-control" id="product_id" >
          @foreach ($products as $product)
            <option value='{{$product->id}}'>{{$product->name}} - stock: {{$product->quantity}}</option>
          @endforeach
        </select>
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <input type="number" name="quantity" id="quantity" class="form-control">
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-outline-primary">
        add sale
      </button>
    </div>
  </form>
</div>
@endsection

resources/views/sale/index.blade.php
@extends('layouts.layout')
@section('content')

<div class='container'>
  <div class="col-md-10">
    <div class="col-md-0 top-10">
      <div class="col-md-12">
        <div class="panel">
          <div class="panel-body">
            <div>
              <h3>Sale</h3>
            </div>

  @include('success')
  @if(count($sales))

  
            <table class='table table-bordered'>
              <tr>
                <th>Item</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
                <th>date</th>
                <th>Action</th>
              </tr>
              <tr>
      @foreach ($sales as $sale)
        
                <tr>
                  <td>{{$sale->product->name}}</td>
                  <td>{{$sale->quantity}}</td>
                  <td>{{$sale->price}}</td>
                  <td>{{$sale->total}}</td>
                  <td>{{$sale->date}}</td>
                  <td>
                    <form action='{{ route('sale.destroy', ['sale' => $sale->id]) }}' class="d-inline" method="post">
              @csrf
              @method('delete')
              
            </form>
                  </td>
                </tr>
      @endforeach
    
              </tr>
            </table>
  {{$sales->links()}}
  
            <ul class="pagination pull-right">
              <a href="{{ route('sales.create') }}" class="btn btn-primary">Add Sales</a>
            </ul>

  @else 
  
            <div class='p-5 text-white bg-danger mb-3'>
              <h3>Look Like You don't have sales!</h3>
            </div>
  @endif

          </div>
@endsection

resources/views/sale/reportpdf.blade.php
<?php

use App\Sale;

$total = 0;

?>
<center>
	<h3>Sales report</h3>
	<br/>
</center>
<div class="header"></div>
<div class="detail">
	<table>
		<tr>
			<th>PS Mini Mart</th>
			<td></td>
		</tr>
	</table>
	<h4>Date Genarate: 
		<?php echo date("m/d/y");?>
	</h4>
</div>
<table border=1 style="width:100%">
	<tr>
		<th>Name</th>
		<th>Remaining</th>
		<th>Price</th>
		<th>Sold</th>
		<th>Earning</th>
	</tr>
	@foreach ($products as $product)
	
	<?php
		$total_product =  Sale::where('product_id', $product->id)->sum('quantity') * $product->price;
		$total += $total_product; 
	?>
	<tr>
		<td>{{ $product->name }}</td>
		<td>{{ $product->quantity }}</td>
		<td>RM {{ $product->price }}</td>
		<td>{{ Sale::where('product_id', $product->id)->sum('quantity') }}</td>
		<td>RM {{ $total_product }}</td>
	</tr>
	@endforeach

</table>
<h3>Total Sales: RM {{ $total }}</h3>