routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/x', function() {
	echo '<form method="post" action="/z">name: <input name="name"/><button type="submit">ok</button></form>';
});

Route::get('/y', 'ProductController@yy');

Route::post('/z', 'ProductController@zz');

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('home');
});

    Route::get('/inventory/report', 'ProductController@report');


Route::group(['middleware' => 'auth'], function () {
  Route::resource('inventory', 'ProductController');

  Route::post('/inventory/{id}/edit', 'ProductController@update');
  Route::post('sale/today', 'SaleController@today')->name('sale.today');
  Route::resource('sales', 'SaleController', ['names' => ['destroy' => 'sale.destroy']]);
  Route::post('/sales/create', 'SaleController@store')->name('sale.create');
  Route::get('/sale/report', 'SaleController@report');

  Route::get('/', 'ProductController@index');


  Route::resource('user', 'StaffController');
  Route::post('/user/{id}/edit', 'StaffController@update');
  Route::get('/', 'StaffController@index');

  //Route::get('/report', 'ReportController@pdf');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout');

resources/views/inventory/create.blade.php
@extends('layouts.layout')
@section('content')
@include('errors')
@include('success')
 
  <div class='container'>
  <div class="col-md-10">
   <div class="col-md-0 top-10">
        <div class="col-md-12">
          <div class="panel">
            <div class="panel-body">
              <div>
            <h3>Edit Inventory</h3>
          </div>
       
        <form method="post" action="{{ route('inventory.store') }}">
          @csrf
          <div class="form-group">
              <label for="name">Product Name</label>
              <input type="text" name="name" id="name" class="form-control">
          </div>
          <div class="form-group">
              <label for="price">Price</label>
              <input type="number" step="0.01" name="price" id="price" class="form-control">
          </div>
          <div class="form-group">
              <label for="quantity">Quantity</label>
              <input type="number" name="quantity" id="quantity" class="form-control">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-success">
              Save
            </button>
          </div>
  </form>
</div>
@endsection

resources/views/inventory/edit.blade.php
@extends('layouts.layout')
@section('content')
<div class='container'>
  
  <div class="col-md-10">

      <div class="col-md-0 top-10">
        <div class="col-md-12">

          <div class="panel">
            <div class="panel-body">
              <div>
    <h3>Edit Inventory</sh3>
  </div>
  <form action="{{ route('inventory.edit', $product->id) }}" method="post">
    @csrf
    <div class="form-group">
        <label for="name">Product Name</label>
        <input type="text" name="name" id="name" value="{{ $product->name }}" class="form-control">
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input type="number" step="0.01" name="price" id="price" value="{{ $product->price }}" class="form-control">
    </div>
    <div class="form-group">
        <label for="quantity">Quantity</label>
        <input type="number" name="quantity" id="quantity" value="{{ $product->quantity }}" class="form-control">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-outline-primary">
        Update
      </button>
    </div>
  </form>
</div>
@endsection

resources/views/inventory/index.blade.php
@extends('layouts.layout')
@section('content')
@include('success')

<div class='container'>
  <div class="col-md-10">
    <div class="col-md-0 top-10">
        <div class="panel">
          <div class="panel-body">
            <div>
              <h3>Inventory</h3>
            </div>
            <div class="col-md-12 padding-0" style="padding-bottom:20px;">
              <div class="col-md-6" style="padding-left:10px;"></div>
              <div class="col-md-6">
                <div class="col-lg-12">
                  <div class="input-group"></div>
                  <!-- /btn-group -->
                </div>
                <!-- /input-group -->
              </div>
              <!-- /.col-lg-6 -->
            </div>
          </div>
          <div class="responsive-table">
            <table class="table table-striped table-bordered" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Price</th>
                  <th>Inventory</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                        @foreach ($products as $product)
                          
                  <tr>
                    <td>{{$product->name}}</td>
                    <td>{{$product->price}}</td>
                    <td>{{$product->quantity}}</td>
                    <td>
                      <form action='{{ route('inventory.destroy', ['inventory' => $product->id]) }}' class="d-inline" method="post" onsubmit = "return confirm('Are you sure?')">
                        <input type="hidden" name="_method" value="DELETE">

                                @csrf
                                @method('delete')
                                
                          <button type="submit" class="btn btn-danger">Delete</button>
                          <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <a href="{{ route('inventory.edit', ['id' => $product->id]) }}" class="btn btn-primary">
                        Update
                        </a>
                          </form>
                        </td>
                      </tr>
                        @endforeach
                      
                    </tr>
                    <tr>
                    </tbody>
                  </table>
                </div>
                <div class="col-md-6" style="padding-top:20px;">
                  <span>showing 0-10 of 30 items</span>
                </div>
                <div class="col-md-6">
                  <ul class="pagination pull-right">
                    <a href="{{ route('inventory.create') }}" class="btn btn-primary">Add Item</a>
                          {{$products->links()}}
                        
                  </ul>
                </div>
                      
                      {{-- 
                <a href="{{ route('inventory.edit.index')}}" class="btn btn-primary">Edit Item</a> --}}
                      
                
              </div>
              <!-- end: content -->
 
@endsection

resources/views/inventory/reportpdf.blade.php
<?php

use App\Product;

use App\Sale;

$totalStockIn = 0;
$totalStockOut = 0;
?>
<center>
    <h3>Inventory report</h3>
    <br/>
</center>
<div class="header"></div>
<div class="detail">
    <table>
        <tr>
            <th>PS Mini Mart</th>
        </tr>
    </table>
    <h4>Date Genarate: 
        <?php echo date("m/d/y");?>
    </h4>
</div>
<table border=1 style="width:100%">
    <tr>
        <th>Name</th>
        <th>Initial Stock</th>
        <th>Sold</th>
        <th>Remaining</th>
    </tr>

    @foreach ($products as $product)

    
    <?php
    $sold = Sale::where('product_id', $product->id)->sum('quantity');

    $totalStockIn += $product->quantity;
    $totalStockOut += $sold;
    ?>
    <tr>
        <td>{{ $product->name }}</td>
        <td>{{ $product->quantity }}</td>
        <td>{{ $sold }}</td>
        <td>{{ $product->quantity - $sold }}</td>
    </tr>
   
    @endforeach

<table border=0 style="width:100%">
    <tr>
        <th><h4>Total Stock In: {{ $totalStockIn }}</h4></th>
        <th><h4>Total Stock Out: {{ $totalStockOut }}</h4></th>
        <th><h4>Available Stock: {{ $totalStockIn - $totalStockOut }}</h4></th>
    </tr>
</table>