routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/x', function() {
	echo '<form method="post" action="/z">name: <input name="name"/><button type="submit">ok</button></form>';
});

Route::get('/y', 'ProductController@yy');

Route::post('/z', 'ProductController@zz');

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('home');
});

    Route::get('/inventory/report', 'ProductController@report');


Route::group(['middleware' => 'auth'], function () {
  Route::resource('inventory', 'ProductController');

  Route::post('/inventory/{id}/edit', 'ProductController@update');
  Route::post('sale/today', 'SaleController@today')->name('sale.today');
  Route::resource('sales', 'SaleController', ['names' => ['destroy' => 'sale.destroy']]);
  Route::post('/sales/create', 'SaleController@store')->name('sale.create');
  Route::get('/sale/report', 'SaleController@report');

  Route::get('/', 'ProductController@index');


  Route::resource('user', 'StaffController');
  Route::post('/user/{id}/edit', 'StaffController@update');
  Route::get('/', 'StaffController@index');

  //Route::get('/report', 'ReportController@pdf');

});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

resources/views/user/create.blade.php
@extends('layouts.layout')
@section('content')
<div class='container'>
  
  <div class="col-md-10">

      <div class="col-md-0 top-10">
        <div class="col-md-12">

          <div class="panel">
            <div class="panel-body">
              <div>
    <h3>Add New Staff</h3>
  </div>
  <form action="{{ route('user.store') }}" method="post">
    @csrf
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-outline-primary">
        Update
      </button>
    </div>
  </form>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.layout')
@section('content')
<div class='container'>
  
  <div class="col-md-10">

      <div class="col-md-0 top-10">
        <div class="col-md-12">

          <div class="panel">
            <div class="panel-body">
              <div>
    <h3>Edit Staff Info</sh3>
  </div>
  <form action="{{ route('user.edit', $user->id) }}" method="post">
    @csrf
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" value="{{ $user->name }}" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" value="{{ $user->email }}" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password" class="form-control">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-outline-primary">
        Update
      </button>
    </div>
  </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.layout')
@section('content')
  @include('success')

<div class='container'>
  
  <div class="col-md-10">

      <div class="col-md-0 top-10">
        <div class="col-md-12">

          <div class="panel">
            <div class="panel-body">
              <div>
              <h3>Manage Staff</h3>
            </div>
              <div class="col-md-12 padding-0" style="padding-bottom:20px;">
                <div class="col-md-6" style="padding-left:10px;">
                    </div>
                    <div class="col-md-6">
                    </div>
                 </div>
                  <div class="responsive-table">
                    <table class="table table-striped table-bordered" width="100%" cellspacing="0">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        @foreach ($users as $user)
                          <tr>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                         
                            <td>
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        
                            <a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-primary">
                        Update
                        </a>
                              </form>
                            </td>
                          </tr>
                        @endforeach
                      </tr>
                      <tr> 
                    </tbody>
                  </table>
                  </div>
                  <div class="col-md-6" style="padding-top:20px;">
                    <span>showing 0-10 of 30 items</span>
                  </div>
                  <div class="col-md-6">
                  </div>
                      <div class="col-md-6" style="padding-left:250px;">
                      <a href="{{ route('user.create') }}" class="btn btn-primary">Add User</a>                  
                </div>
</tr>
</tbody>

          <!-- end: content -->
 
@endsection